<?php

namespace common\models;

use Yii;

/**
 * 这是表 `data_all` 的模型
 */
class DataSr0 extends \common\components\ARModel
{

public function afterFind()
{
    parent::afterFind(); // TODO: Change the autogenerated stub
    $this->Name = 'das';
}
}
